accepted: true
base_seed: 0
counts:
  I_full_pairs: 8
  I_pairs: 8
  edges_true: 20
data_spec:
  d: 10
  graph_type: ER
  n: 1000
  noise_scale: 1.0
  s0: 20
  sem_type: gauss
  w_ranges:
  - - -2.0
    - -0.5
  - - 0.5
    - 2.0
dataset_id: '6'
descr: lin_sem_er
i_spec:
  alpha: 0.001
  bonferroni: true
  cap: null
  cap_seed: 1
  min_indeps: 1
  num_perm: 500
  seed: 0
  source: oracle
  test: spearman
  undirected: false
paths:
  B_true: true/B_true.npy
  I: true/I.npy
  I_full: true/I_full.npy
  W_true: true/W_true.npy
  X: X.npy
  meta: meta.yaml
shapes:
  B_true:
  - 10
  - 10
  I:
  - 8
  - 2
  I_full:
  - 8
  - 2
  W_true:
  - 10
  - 10
  X:
  - 1000
  - 10
subkey:
- 1797259609
- 2579123966
try: 5
walltime_min: 0.013847204049428304
